# Generated by Django 2.1.5 on 2020-07-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Script_code', models.IntegerField()),
                ('Name', models.CharField(max_length=160)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('High', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Low', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
